dataset:
  type: 'dair'
  data_dir: '/home/javier/datasets/DAIR-V2X/single-infrastructure-side'
  split_dir: '/home/javier/datasets/DAIR-V2X/single-infrastructure-side-mmdet'
  label_dir: '/home/javier/datasets/DAIR-V2X/single-infrastructure-side/label'
  eval_cls: ['Car','Pedestrian','Cyclist']
  batch_size: 6
  num_workers: 16
  class_merging: False
  use_dontcare: False
  use_3d_center: True
  writelist: ['Car','Pedestrian','Cyclist']
  random_flip: 0.5
  random_crop: 0.5
  # random_mix: 0.5 UPDATE
  scale: 0.4
  shift: 0.1
  drop_last_val: True
  cls_mean_size: [[1.69076256, 1.95625980, 4.59149442],
                  [1.64686968, 0.56291266, 0.52403671],
                  [1.42871768, 0.64937362, 1.68556033]]
  cls_num: 3
  max_objs: 100
  resolution: [1920, 1088]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  downsample: 4

model:
  type: 'SMOKE'
  backbone: 'dla34'
  neck: 'DLAUp'
  head: 'SmokeHead'
  loss: 'asfd'
  downsample: 4
  loss_weight: [10., 5.]
  depth_ref: [28.01, 16.32]


optimizer:
  type: 'adam'
  lr: 0.001
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  # decay_list: [240, 360, 480]
  decay_list: [60, 90, 120]

trainer:
  max_epoch: 150
  eval_start: 15
  eval_frequency: 15 # evaluation interval (in epoch)
  save_frequency: 50 # checkpoint save interval (in epoch)
  disp_frequency: 10 # display interval (in batch)
  log_dir: 'work_dirs/SMOKE_DAIR_150e/logs/'
  out_dir: 'work_dirs/SMOKE_DAIR_150e/output/'
  resume_model: ''

tester:
  threshold: 0.2  # confidence filter
  top_k: 50  # max number of boxes
  out_dir: './SMOKE_DAIR_150e/testset_out'
  resume_model: '' # pre-trained model path


wandb:
  name: "SMOKE_DAIR_150e"
  notes: "SMOKE trained on DAIR during 150e"

