dataset:
  type: 'kitti'
  data_dir: '/home/javier/datasets/kitti'
  label_dir: '/home/javier/datasets/kitti/training/label_2'
  eval_cls: ['Car','Pedestrian','Cyclist']
  batch_size: 24
  num_workers: 16
  class_merging: False
  use_dontcare: False
  use_3d_center: True
  writelist: ['Car','Pedestrian','Cyclist']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1
  drop_last_val: True
  cls_mean_size: [[1.76255119, 0.66068622, 0.84422524],
                  [1.52563191, 1.6285674,  3.8831164 ],
                  [1.73698127, 0.59706367, 1.76282397]]
  cls_num: 3

model:
  type: 'SMOKE'
  backbone: 'dla34'
  neck: 'DLAUp'
  head: 'SmokeHead'
  loss: 'asfd'
  downsample: 4
  loss_weight: [10., 5.]



optimizer:
  type: 'adam'
  lr: 0.001
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.8
  # decay_list: [240, 360, 480]
  decay_list: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140]

trainer:
  max_epoch: 150
  eval_start: 50
  eval_frequency: 10 # evaluation interval (in epoch)
  save_frequency: 50 # checkpoint save interval (in epoch)
  disp_frequency: 50 # display interval (in batch)
  log_dir: 'work_dirs/SMOKE/logs/'
  out_dir: 'work_dirs/SMOKE/output/'
  # resume_model: ''

tester:
  threshold: 0.2  # confidence filter
  out_dir: './SMOKE/testset_out'
  resume_model: '/home/javier/pytorch/RoadVision3D/work_dirs/MonoLSS_good/MonoLSS_v2/logs/checkpoints/checkpoint_epoch_150.pth' # pre-trained model path



