dataset:
  type: 'kitti'
  data_dir: '/home/javier/datasets/kitti'
  root_dir: '/'
  label_dir: '/home/javier/datasets/kitti/training/label_2'
  eval_cls: ['Car','Pedestrian','Cyclist']
  batch_size: 24
  num_workers: 16
  class_merging: False
  use_dontcare: False
  use_3d_center: True
  writelist: ['Car','Pedestrian','Cyclist']
  random_flip: 0.5
  random_crop: 0.5
  scale: 0.4
  shift: 0.1
  drop_last_val: True

model:
  type: 'MonoLSS'
  backbone: 'dla34'
  neck: 'DLAUp'

optimizer:
  type: 'adam'
  lr: 0.001
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  # decay_list: [240, 360, 480]
  decay_list: [90, 120]

trainer:
  max_epoch: 150
  eval_start: 60
  eval_frequency: 60 # evaluation interval (in epoch)
  save_frequency: 60 # checkpoint save interval (in epoch)
  disp_frequency: 50 # display interval (in batch)
  log_dir: 'work_dirs/MonoLSS/logs/'
  out_dir: 'work_dirs/MonoLSS/output/'
  # resume_model: ''

tester:
  threshold: 0.2  # confidence filter
  out_dir: './MonoLSS/testset_out'
  resume_model: '/home/javier/pytorch/RoadVision3D/work_dirs/MonoLSS/logs/checkpoints/checkpoint_epoch_600.pth' # pre-trained model path



