dataset:
  type: 'kitti'
  data_dir: '/home/javier/datasets/kitti'
  label_dir: '/home/javier/datasets/kitti/training/label_2'
  split_dir: '/home/javier/pytorch/splits/KITTI_reduced'
  eval_cls: ['Car']
  batch_size: 24
  num_workers: 16
  class_merging: False
  use_dontcare: False
  use_3d_center: True
  writelist: ['Car']
  random_flip: 0
  random_crop: 0
  random_mix: 0
  scale: 0
  shift: 0
  drop_last_val: True
  cls_mean_size: [[1.52563191, 1.6285674,  3.8831164 ]]
  cls_num: 1
  max_objs: 50
  resolution: [1280, 384]
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  downsample: 4

model:
  type: 'MonoLSS'
  backbone: 'dla34'
  neck: 'DLAUp'
  head: 'MonoLSSHead'
  loss: 'LSS_Loss'
  downsample: 4


optimizer:
  type: 'adam'
  lr: 0.001
  weight_decay: 0.00001

lr_scheduler:
  warmup: True  # 5 epoches, cosine warmup, init_lir=0.00001 in default
  decay_rate: 0.1
  # decay_list: [240, 360, 480]
  decay_list: [90, 120]

trainer:
  max_epoch: 150
  eval_start: 10
  eval_frequency: 10 # evaluation interval (in epoch)
  save_frequency: 50 # checkpoint save interval (in epoch)
  disp_frequency: 10 # display interval (in batch)
  log_dir: 'work_dirs/MonoLSS_KITTI_EXP/logs/'
  out_dir: 'work_dirs/MonoLSS_KITTI_EXP/output/'
  # resume_model: ''

tester:
  threshold: 0.2  # confidence filter
  top_k: 50  # max number of boxes
  out_dir: './KITTI_EXP/testset_out'
  resume_model: '/home/javier/pytorch/RoadVision3D/work_dirs/MonoLSS/KITTI_EXP/logs/checkpoints/checkpoint_epoch_150.pth' # pre-trained model path


wandb:
  name: "Experiments"
  notes: "MonoLSS EXP trained on Reduced KITTI over 150e"

